default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: salary_management_api_development

test:
  <<: *default
  database: salary_management_api_test

production:
  <<: *default
  database: salary_management_api_production
  username: salary_management_api
  password: <%= ENV["SALARY_MANAGEMENT_API_DATABASE_PASSWORD"] %>
